spring:
  profiles:
    active: dev
  application:
    name: voteSystem
#mybatis-plus配置
mybatis-plus:
  #Mapper
  mapper-locations: classpath:mapper/*.xml

# 日志
logging:
  level:
    com.jd.mapper: debug

